name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
      - name: Set up Go 1.22
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Test
        run: go test ./...
